-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:13:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bikraft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bikraft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bikraft` DEFAULT CHARACTER SET utf8 ;
USE `bikraft` ;

-- -----------------------------------------------------
-- Table `bikraft`.`clientes_01`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`clientes_01` (
  `t01_idCliente` INT NOT NULL AUTO_INCREMENT,
  `t01_nome` VARCHAR(60) NULL,
  `t01_cpf` VARCHAR(20) NULL,
  `t01_fone` VARCHAR(16) NULL,
  `t01_celular` VARCHAR(16) NULL,
  `t01_dtNascimento` DATE NULL,
  `t01_sexo` VARCHAR(12) NULL,
  `t01_email` VARCHAR(60) NULL,
  `t01_senha` VARCHAR(45) NULL,
  PRIMARY KEY (`t01_idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`cartoes_02`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`cartoes_02` (
  `t02_idCartao` INT NOT NULL AUTO_INCREMENT,
  `t02_numCartao` VARCHAR(17) NULL,
  `t02_bandeita` VARCHAR(45) NULL,
  `t02_vencimento` VARCHAR(45) NULL,
  `t02_titular` VARCHAR(60) NULL,
  `t01_idCliente` INT NULL,
  PRIMARY KEY (`t02_idCartao`),
  INDEX `CLIENTE_idx` (`t01_idCliente` ASC) VISIBLE,
  CONSTRAINT `CLIENTE`
    FOREIGN KEY (`t01_idCliente`)
    REFERENCES `bikraft`.`clientes_01` (`t01_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`entregas_03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`entregas_03` (
  `t03_idEntrega` INT NOT NULL AUTO_INCREMENT,
  `t01_idCliente` INT NULL,
  `t03_endereco` VARCHAR(60) NULL,
  `t03_bairro` VARCHAR(45) NULL,
  `t03_cep` VARCHAR(10) NULL,
  `t03_cidade` VARCHAR(45) NULL,
  `t03_estado` VARCHAR(3) NULL,
  PRIMARY KEY (`t03_idEntrega`),
  INDEX `CLIENTE_idx` (`t01_idCliente` ASC) VISIBLE,
  CONSTRAINT `CLIENTE`
    FOREIGN KEY (`t01_idCliente`)
    REFERENCES `bikraft`.`clientes_01` (`t01_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`fabricates_07`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`fabricates_07` (
  `t07_idFabricantes` INT NOT NULL AUTO_INCREMENT,
  `t07_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`t07_idFabricantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`pecas_04`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`pecas_04` (
  `t04_idpecas` INT NOT NULL AUTO_INCREMENT,
  `t04_nome` VARCHAR(60) NULL,
  `t04_material` VARCHAR(45) NULL,
  `t04_cor` VARCHAR(45) NULL,
  `t07_fabricante` INT NULL,
  PRIMARY KEY (`t04_idpecas`),
  INDEX `FABRICANTES_idx` (`t07_fabricante` ASC) VISIBLE,
  CONSTRAINT `FABRICANTES`
    FOREIGN KEY (`t07_fabricante`)
    REFERENCES `bikraft`.`fabricates_07` (`t07_idFabricantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`modalidades_05`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`modalidades_05` (
  `t05_idModalidade` INT NOT NULL AUTO_INCREMENT,
  `t05_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`t05_idModalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`pecasModaldades_06`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`pecasModaldades_06` (
  `t06_idPecaModalidade` INT NOT NULL AUTO_INCREMENT,
  `t04_idPeca` INT NULL,
  `t05_idModalidade` INT NULL,
  PRIMARY KEY (`t06_idPecaModalidade`),
  INDEX `PECAS_idx` (`t04_idPeca` ASC) VISIBLE,
  INDEX `MODALIDADES_idx` (`t05_idModalidade` ASC) VISIBLE,
  CONSTRAINT `PECAS`
    FOREIGN KEY (`t04_idPeca`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MODALIDADES`
    FOREIGN KEY (`t05_idModalidade`)
    REFERENCES `bikraft`.`modalidades_05` (`t05_idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`produtos_08`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`produtos_08` (
  `t08_idProduto` INT NOT NULL AUTO_INCREMENT,
  `t08_nome` VARCHAR(45) NULL,
  `t08_quadro` INT NULL,
  `t08_aro` INT NULL,
  `t08_relacao` INT NULL,
  `t08_cubo` INT NULL,
  `t08_pedevela` INT NULL,
  `t08_pedal` INT NULL,
  `t08_guidao` INT NULL,
  `t08_caxaDirecao` INT NULL,
  `t08_mesa` INT NULL,
  `t08_selim` INT NULL,
  `t08_freio` INT NULL,
  `t08_manete` INT NULL,
  `t08_manopla` INT NULL,
  `t08_valor` DECIMAL(9,2) NULL,
  PRIMARY KEY (`t08_idProduto`),
  INDEX `QUADRO_idx` (`t08_quadro` ASC) VISIBLE,
  INDEX `ARO_idx` (`t08_aro` ASC) VISIBLE,
  INDEX `RELACAO_idx` (`t08_relacao` ASC) VISIBLE,
  INDEX `CUBO_idx` (`t08_cubo` ASC) VISIBLE,
  INDEX `PEDAL_idx` (`t08_pedal` ASC) VISIBLE,
  INDEX `QUIDAO_idx` (`t08_guidao` ASC) VISIBLE,
  INDEX `CAIXADIRECAO_idx` (`t08_caxaDirecao` ASC) VISIBLE,
  INDEX `MESA_idx` (`t08_mesa` ASC) VISIBLE,
  INDEX `SELIM_idx` (`t08_selim` ASC) VISIBLE,
  INDEX `FREIO_idx` (`t08_freio` ASC) VISIBLE,
  INDEX `MANETE_idx` (`t08_manete` ASC) VISIBLE,
  INDEX `MANOPLA_idx` (`t08_manopla` ASC) VISIBLE,
  INDEX `PEDEVELA_idx` (`t08_pedevela` ASC) VISIBLE,
  CONSTRAINT `QUADRO`
    FOREIGN KEY (`t08_quadro`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARO`
    FOREIGN KEY (`t08_aro`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RELACAO`
    FOREIGN KEY (`t08_relacao`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CUBO`
    FOREIGN KEY (`t08_cubo`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDEVELA`
    FOREIGN KEY (`t08_pedevela`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDAL`
    FOREIGN KEY (`t08_pedal`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `QUIDAO`
    FOREIGN KEY (`t08_guidao`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CAIXADIRECAO`
    FOREIGN KEY (`t08_caxaDirecao`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MESA`
    FOREIGN KEY (`t08_mesa`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SELIM`
    FOREIGN KEY (`t08_selim`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FREIO`
    FOREIGN KEY (`t08_freio`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MANETE`
    FOREIGN KEY (`t08_manete`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MANOPLA`
    FOREIGN KEY (`t08_manopla`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`custon_09`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`custon_09` (
  `t09_idCuston` INT NOT NULL AUTO_INCREMENT,
  `t01_idCliente` INT NULL,
  `t09_quadro` INT NULL,
  `t09_aro` INT NULL,
  `t09_relacao` INT NULL,
  `t09_cubo` INT NULL,
  `t09_pedevela` INT NULL,
  `t09_pedal` INT NULL,
  `t09_guidao` INT NULL,
  `t09_caxaDirecao` INT NULL,
  `t09_mesa` INT NULL,
  `t09_selim` INT NULL,
  `t09_freio` INT NULL,
  `t09_manete` INT NULL,
  `t09_manopla` INT NULL,
  PRIMARY KEY (`t09_idCuston`),
  INDEX `QUADRO_idx` (`t09_quadro` ASC) VISIBLE,
  INDEX `ARO_idx` (`t09_aro` ASC) VISIBLE,
  INDEX `RELACAO_idx` (`t09_relacao` ASC) VISIBLE,
  INDEX `CUBO_idx` (`t09_cubo` ASC) VISIBLE,
  INDEX `PEDAL_idx` (`t09_pedal` ASC) VISIBLE,
  INDEX `QUIDAO_idx` (`t09_guidao` ASC) VISIBLE,
  INDEX `CAIXADIRECAO_idx` (`t09_caxaDirecao` ASC) VISIBLE,
  INDEX `MESA_idx` (`t09_mesa` ASC) VISIBLE,
  INDEX `SELIM_idx` (`t09_selim` ASC) VISIBLE,
  INDEX `FREIO_idx` (`t09_freio` ASC) VISIBLE,
  INDEX `MANETE_idx` (`t09_manete` ASC) VISIBLE,
  INDEX `MANOPLA_idx` (`t09_manopla` ASC) VISIBLE,
  INDEX `PEDEVELA_idx` (`t09_pedevela` ASC) VISIBLE,
  CONSTRAINT `QUADRO0`
    FOREIGN KEY (`t09_quadro`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARO0`
    FOREIGN KEY (`t09_aro`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RELACAO0`
    FOREIGN KEY (`t09_relacao`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CUBO0`
    FOREIGN KEY (`t09_cubo`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDEVELA0`
    FOREIGN KEY (`t09_pedevela`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDAL0`
    FOREIGN KEY (`t09_pedal`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `QUIDAO0`
    FOREIGN KEY (`t09_guidao`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CAIXADIRECAO0`
    FOREIGN KEY (`t09_caxaDirecao`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MESA0`
    FOREIGN KEY (`t09_mesa`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SELIM0`
    FOREIGN KEY (`t09_selim`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FREIO0`
    FOREIGN KEY (`t09_freio`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MANETE0`
    FOREIGN KEY (`t09_manete`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MANOPLA0`
    FOREIGN KEY (`t09_manopla`)
    REFERENCES `bikraft`.`pecas_04` (`t04_idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`valores_10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`valores_10` (
  `t10_idValor` INT NOT NULL AUTO_INCREMENT,
  `t09_custon` INT NULL,
  `t10_valor` DECIMAL(9,2) NULL,
  PRIMARY KEY (`t10_idValor`),
  INDEX `CUSTON_idx` (`t09_custon` ASC) VISIBLE,
  CONSTRAINT `CUSTON`
    FOREIGN KEY (`t09_custon`)
    REFERENCES `bikraft`.`custon_09` (`t09_idCuston`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`pedido_11`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`pedido_11` (
  `t11_idpedido` INT NOT NULL AUTO_INCREMENT,
  `t09_idcuston` INT NULL,
  `t01_idCliente` INT NULL,
  `t03_idEntrega` INT NULL,
  PRIMARY KEY (`t11_idpedido`),
  INDEX `CUSTON_idx` (`t09_idcuston` ASC) VISIBLE,
  INDEX `CLIENTE_idx` (`t01_idCliente` ASC) VISIBLE,
  INDEX `ENTREGA_idx` (`t03_idEntrega` ASC) VISIBLE,
  CONSTRAINT `CUSTON`
    FOREIGN KEY (`t09_idcuston`)
    REFERENCES `bikraft`.`custon_09` (`t09_idCuston`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CLIENTE`
    FOREIGN KEY (`t01_idCliente`)
    REFERENCES `bikraft`.`clientes_01` (`t01_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ENTREGA`
    FOREIGN KEY (`t03_idEntrega`)
    REFERENCES `bikraft`.`entregas_03` (`t03_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikraft`.`pagamentos_12`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikraft`.`pagamentos_12` (
  `t12_idPagamento` INT NOT NULL,
  `t02_idCartao` INT NULL,
  `t12_valor` DECIMAL(9,2) NULL,
  `t11_pedido` INT NULL,
  PRIMARY KEY (`t12_idPagamento`),
  INDEX `CARTAO_idx` (`t02_idCartao` ASC) VISIBLE,
  INDEX `PEDIDO_idx` (`t11_pedido` ASC) VISIBLE,
  CONSTRAINT `CARTAO`
    FOREIGN KEY (`t02_idCartao`)
    REFERENCES `bikraft`.`cartoes_02` (`t02_idCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDIDO`
    FOREIGN KEY (`t11_pedido`)
    REFERENCES `bikraft`.`pedido_11` (`t11_idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
